# Generated by Django 3.1.2 on 2020-10-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
