# Generated by Django 3.1 on 2020-09-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='platform',
            field=models.CharField(choices=[('shopify', 'Shopify')], max_length=30, null=True),
        ),
    ]
