# Generated by Django 3.1.2 on 2020-11-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_vendor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(related_name='favourites', to='dashboard.Vendor'),
        ),
    ]
