# Generated by Django 3.1.2 on 2020-11-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_profile_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='commission',
            field=models.DecimalField(decimal_places=4, default=0, help_text='The vendor commission rate, set it as a decimal e.g. 15% = 0.15', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to='dashboard.Vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='The store name within the shopify url', max_length=30, unique=True),
        ),
    ]
