# Generated by Django 3.1 on 2020-09-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200902_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='api_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='api_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
