# Generated by Django 3.1.2 on 2020-11-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201113_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='free_shipping',
            field=models.DecimalField(decimal_places=4, help_text='The vendors current free shipping threshold', max_digits=10, null=True),
        ),
    ]
