# Generated by Django 3.1 on 2020-09-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200902_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce')], max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='api_password',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='api_username',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='platform',
        ),
        migrations.CreateModel(
            name='VendorPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_username', models.CharField(blank=True, max_length=200, null=True)),
                ('api_password', models.CharField(blank=True, max_length=200, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.platform')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='platform',
            field=models.ManyToManyField(through='dashboard.VendorPlatform', to='dashboard.Platform'),
        ),
    ]
