# Generated by Django 3.1 on 2020-09-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200903_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce')], max_length=30, null=True, unique=True),
        ),
    ]
