# Generated by Django 3.1.2 on 2020-11-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201121_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='commission',
            field=models.DecimalField(decimal_places=4, help_text='The vendor commission rate, set it as a decimal e.g. 15% = 0.15', max_digits=10, null=True),
        ),
    ]
