# Generated by Django 3.1.3 on 2020-11-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201122_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
