# Generated by Django 3.1.1 on 2020-09-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200903_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.platform')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'platform')},
            },
        ),
        migrations.DeleteModel(
            name='VendorPlatform',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='platform',
            field=models.ManyToManyField(through='dashboard.APICredentials', to='dashboard.Platform'),
        ),
    ]
