# Generated by Django 3.1.1 on 2020-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200904_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APICredentials',
            new_name='APICredential',
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('woocommerce', 'WooCommerce'), ('shopify', 'Shopify')], max_length=30, null=True, unique=True),
        ),
    ]
