# Generated by Django 3.1.1 on 2020-09-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200904_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='categories',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
