# Generated by Django 3.1.1 on 2020-09-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200907_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('woocommerce', 'WooCommerce'), ('shopify', 'Shopify')], max_length=30, null=True, unique=True),
        ),
    ]
