# Generated by Django 3.1.1 on 2020-09-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200908_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
