# Generated by Django 3.1.1 on 2020-09-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200921_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='scopes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
