# Generated by Django 3.1.1 on 2020-09-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_apicredential_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='storefront_access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
