# Generated by Django 3.1.1 on 2020-10-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_apicredential_storefront_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.BooleanField(default=False),
        ),
    ]
