# Generated by Django 3.1.1 on 2020-10-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='sales_channel_endpoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='storefront_endpoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
