# Generated by Django 3.1.1 on 2020-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20201006_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='email_pref',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_vendor',
            field=models.BooleanField(null=True),
        ),
    ]
