# Generated by Django 3.1.1 on 2020-10-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201012_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
