# Generated by Django 3.1 on 2020-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_src',
            field=models.URLField(null=True),
        ),
    ]
