# Generated by Django 3.1.1 on 2020-10-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_attribute_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='order',
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Used to order sizing in the store, 1 is the smallest', null=True),
        ),
    ]
