# Generated by Django 3.1.1 on 2020-09-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200906_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='dsajdkjaskldklajfklas', max_length=100),
            preserve_default=False,
        ),
    ]
