# Generated by Django 3.1.1 on 2020-09-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='value_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Text'),
        ),
    ]
