# Generated by Django 3.1.1 on 2020-09-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('dashboard', '0016_auto_20200915_1642'),
        ('product', '0017_auto_20200915_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttributeGroup',
            new_name='CategoryAttributeGroup',
        ),
        migrations.CreateModel(
            name='SizeGuideItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('attribute', models.ManyToManyField(to='product.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='SizeGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor')),
            ],
        ),
    ]
