# Generated by Django 3.1.1 on 2020-09-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20200920_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='value_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attributeoption'),
        ),
        migrations.AlterField(
            model_name='attributeoption',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.attributeoptiongroup'),
        ),
    ]
