# Generated by Django 3.1.1 on 2020-09-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20200920_0941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'product')},
        ),
    ]
