# Generated by Django 3.1.1 on 2020-09-24 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200921_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeguideitem',
            name='size_guide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.sizeguide'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
