# Generated by Django 3.1.1 on 2020-09-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200924_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='product.Size'),
        ),
        migrations.AddField(
            model_name='sizeguideitem',
            name='size',
            field=models.ManyToManyField(to='product.Size'),
        ),
    ]
