# Generated by Django 3.1.1 on 2020-09-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20200924_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Used to order the sizes, 1 is the smallest'),
            preserve_default=False,
        ),
    ]
