# Generated by Django 3.1.1 on 2020-10-01 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_apicredential_storefront_access_token'),
        ('product', '0026_size_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.sizeguide'),
        ),
        migrations.AlterUniqueTogether(
            name='sizeguide',
            unique_together={('name', 'vendor')},
        ),
    ]
