# Generated by Django 3.1.1 on 2020-10-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20201001_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Only choose a parent product if you're creating a variant variant.  For example if this is a size 4 of a particular t-shirt.  Leave blank if this is a stand-alone product (i.e. there is only one version of this product).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.product', verbose_name='Parent product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('standalone', 'Stand-alone product'), ('parent', 'Parent product'), ('variant', 'Variant product')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.sizeguide'),
        ),
    ]
