# Generated by Django 3.1.1 on 2020-10-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_attribute_size_guide_info'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sizeguideitem',
            unique_together={('size_guide', 'size', 'attribute')},
        ),
    ]
