# Generated by Django 3.1.2 on 2020-10-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
